// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMC1-2BXRMX4J53cPXtdKhhbWI_hx4wLU',
    appId: '1:662729051328:web:6c8fdf926c5ffcfe683125',
    messagingSenderId: '662729051328',
    projectId: 'crypto-coins-list-d261d',
    authDomain: 'crypto-coins-list-d261d.firebaseapp.com',
    storageBucket: 'crypto-coins-list-d261d.appspot.com',
    measurementId: 'G-GGB0G0S7N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfL7qxt7knxZU8IEBEMjZArxt7p3KwCmA',
    appId: '1:662729051328:android:4f77125e0ca81c58683125',
    messagingSenderId: '662729051328',
    projectId: 'crypto-coins-list-d261d',
    storageBucket: 'crypto-coins-list-d261d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMC1-2BXRMX4J53cPXtdKhhbWI_hx4wLU',
    appId: '1:662729051328:web:84433f4fa77e5bfe683125',
    messagingSenderId: '662729051328',
    projectId: 'crypto-coins-list-d261d',
    authDomain: 'crypto-coins-list-d261d.firebaseapp.com',
    storageBucket: 'crypto-coins-list-d261d.appspot.com',
    measurementId: 'G-6FZ30NCW04',
  );
}
